/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface JmStockPrice {
        "stockSymbol": string;
    }
}
declare global {
    interface HTMLJmStockPriceElement extends Components.JmStockPrice, HTMLStencilElement {
    }
    var HTMLJmStockPriceElement: {
        prototype: HTMLJmStockPriceElement;
        new (): HTMLJmStockPriceElement;
    };
    interface HTMLElementTagNameMap {
        "jm-stock-price": HTMLJmStockPriceElement;
    }
}
declare namespace LocalJSX {
    interface JmStockPrice {
        "stockSymbol"?: string;
    }
    interface IntrinsicElements {
        "jm-stock-price": JmStockPrice;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "jm-stock-price": LocalJSX.JmStockPrice & JSXBase.HTMLAttributes<HTMLJmStockPriceElement>;
        }
    }
}
