/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface JmSpinner {
    }
    interface JmStockFinder {
    }
    interface JmStockPrice {
        "stockSymbol": string;
    }
}
declare global {
    interface HTMLJmSpinnerElement extends Components.JmSpinner, HTMLStencilElement {
    }
    var HTMLJmSpinnerElement: {
        prototype: HTMLJmSpinnerElement;
        new (): HTMLJmSpinnerElement;
    };
    interface HTMLJmStockFinderElement extends Components.JmStockFinder, HTMLStencilElement {
    }
    var HTMLJmStockFinderElement: {
        prototype: HTMLJmStockFinderElement;
        new (): HTMLJmStockFinderElement;
    };
    interface HTMLJmStockPriceElement extends Components.JmStockPrice, HTMLStencilElement {
    }
    var HTMLJmStockPriceElement: {
        prototype: HTMLJmStockPriceElement;
        new (): HTMLJmStockPriceElement;
    };
    interface HTMLElementTagNameMap {
        "jm-spinner": HTMLJmSpinnerElement;
        "jm-stock-finder": HTMLJmStockFinderElement;
        "jm-stock-price": HTMLJmStockPriceElement;
    }
}
declare namespace LocalJSX {
    interface JmSpinner {
    }
    interface JmStockFinder {
        "onJmSymbolSelected"?: (event: CustomEvent<string>) => void;
    }
    interface JmStockPrice {
        "stockSymbol"?: string;
    }
    interface IntrinsicElements {
        "jm-spinner": JmSpinner;
        "jm-stock-finder": JmStockFinder;
        "jm-stock-price": JmStockPrice;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "jm-spinner": LocalJSX.JmSpinner & JSXBase.HTMLAttributes<HTMLJmSpinnerElement>;
            "jm-stock-finder": LocalJSX.JmStockFinder & JSXBase.HTMLAttributes<HTMLJmStockFinderElement>;
            "jm-stock-price": LocalJSX.JmStockPrice & JSXBase.HTMLAttributes<HTMLJmStockPriceElement>;
        }
    }
}
